name: ml-client
services:
  - name: ml-client-service
    dockerfile_path: machine-learning-client/Dockerfile
    source_dir: machine-learning-client
    run_command: "python app.py"
    environment_slug: docker
    envs:
      - key: MONGO_URI
        scope: RUN_AND_BUILD_TIME
        value: your_mongo_uri_here
