name: Machine Learning Client CI/CD

on:
  push:
    branches: [main, master]
    paths:
      - 'machine-learning-client/**'
  pull_request:
    branches: [main, master]
    paths:
      - 'machine-learning-client/**'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/ml-client

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies and run tests
      working-directory: ./machine-learning-client
      run: |
        pip install -r requirements.txt
        pip install pytest pytest-cov
        pytest --cov=./ --cov-fail-under=80

    - name: Build Docker image
      working-directory: ./machine-learning-client
      run: |
        docker build -t $IMAGE_NAME:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push $IMAGE_NAME:latest
    
    
    # Optional: Deploy to DigitalOcean if needed
    - name: Deploy to DigitalOcean App Platform
      uses: digitalocean/app-action@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        spec: |
          name: your-ml-client-app-name
          region: nyc1
          services:
            - name: ml-client
              dockerfile_path: ./machine-learning-client/Dockerfile
              source_dir: ./machine-learning-client
              envs:
                - key: MONGO_URI
                  value: ${{ secrets.MONGO_URI }}

