name: CI/CD Pipeline for Machine Learning Client

on:
  push:
    branches: [main, master]
    paths:
      - 'machine-learning-client/**'
  pull_request:
    branches: [main, master]
    paths:
      - 'machine-learning-client/**'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/ml-client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies and run tests
        working-directory: ./machine-learning-client
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov
          pytest --cov=./ --cov-fail-under=80

      - name: Build Docker image
        working-directory: ./machine-learning-client
        run: |
          docker build -t $IMAGE_NAME:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push $IMAGE_NAME:latest

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Deploy to DigitalOcean App Platform
        run: |
          # Deploy to DigitalOcean using doctl
          doctl apps create --spec app.yaml || doctl apps update ${{ secrets.DO_APP_ID }} --spec app.yaml
          
      - name: Install Pipenv
        run: |
          python -m pip install pipenv
      
      - name: Install NLTK data
        run: |
          python -m nltk.downloader punkt stopwords wordnet
        env:
          NLTK_DATA: /home/runner/nltk_data 
      - name: Verify pytest-cov Installation
        run: |
          pip show pytest-cov
      
      - name: Run Tests
        working-directory: machine-learning-client
        run: |
          pytest --cov=app.py --cov-report=xml
      - name: Install spaCy model
        run: |
              python -m spacy download en_core_web_sm-3.7.0
        
      
