name: CI/CD Pipeline for Web App

on:
  push:
    branches: [main, master]
    paths:
      - 'web-app/**'
  pull_request:
    branches: [main, master]
    paths:
      - 'web-app/**'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/web-app

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies and run tests
      working-directory: ./web-app
      run: |
        pip install -r requirements.txt
        pip install pytest pytest-cov
        pytest --cov=./ --cov-fail-under=80

    - name: Build Docker image
      working-directory: ./web-app
      run: |
        docker build -t $IMAGE_NAME:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push $IMAGE_NAME:latest

    - name: Deploy to DigitalOcean App Platform
      uses: digitalocean/app-action@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        spec: |
          name: your-app-name
          region: nyc1
          services:
            - name: web-app
              dockerfile_path: ./web-app/Dockerfile
              source_dir: ./web-app
              envs:
                - key: MONGO_URI
                  value: ${{ secrets.MONGO_URI }}
