name: CI/CD Pipeline for Web App

on:
  push:
    branches: [main, master]
    paths:
      - 'web-app/**'
      - 'docker-compose.yaml'
      - '.github/workflows/**'
  pull_request:
    branches: [main, master]
    paths:
      - 'web-app/**'
      - 'docker-compose.yaml'
      - '.github/workflows/**'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/web-app

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build Docker image
        working-directory: ./web-app
        run: |
          docker build -t $IMAGE_NAME:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push $IMAGE_NAME:latest

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}


      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r web-app/requirements.txt
  
      - name: Download NLTK Data
        run: |
          python -m nltk.downloader punkt punkt_tab

      - name: Run Tests
        working-directory: web-app
        run: |
          pytest --cov=app --cov-fail-under=80 --cov-report=xml

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |
            cd 5-final-garage4
            docker compose pull
            docker compose up -d

          
